### ISSUE TITLE
When would you update your code?

### ISSUE THREAD

**Issue by ShaoqiLee** [NVlabs/few_shot_gaze#1]
When would you update your code? Thanks

**Comment by swook** [comment]
Hi there, sorry about the late response. I will be attempting to upload the by the presentation date of 1st November, but unfortunately cannot guarantee this. Apologies for that!

I will release the dataset pre-processing code earlier.

**Comment by ShokanTK** [comment]
Would you add training code?

**Comment by swook** [comment]
Yes, this is very much the intention. Unfortunately the release of the code is further delayed.

**Comment by jswati31** [comment]
Hi, 
your work is very interesting and I am really looking forward to the source code. When would you be able to update it?

Thanks. :)

**Comment by swook** [comment]
Hello there! Sorry about the delays from our end. We are trying to get the code released as quickly as possible, but unfortunately have hit a few delays. Please watch the repository to get notified when the code is finally pushed. Again, apologies for the delays!

**Comment by jelleopard** [comment]
Hi,
Looking forward to your source code, I have been waiting this for one month. 
Could you please tell me the framework in your work, torch, tf or caffe?

Thank you.

**Comment by ymohit** [comment]
> Hi,
> Looking forward to your source code, I have been waiting this for one month.
> Could you please tell me the framework in your work, torch, tf or caffe?
> 
> Thank you.

It's torch. You can check the pull request. https://github.com/NVlabs/few_shot_gaze/pull/2/commits/a2cf1a714acdc2840b71fc21e1700030f6a4bf29.
