### ISSUE TITLE
"Current thread is not the object's thread" and "Segmentation fault (core dumped)" error

### ISSUE THREAD

**Issue by san9569** [NVlabs/few_shot_gaze#13]
Hi, I'm trying to exec `run_demo.py`. but this warning below (maybe error) appear repeatedly
```
QObject::moveToThread: Current thread (0x55af5ad9b920) is not the object's thread (0x55af5cb91700).
Cannot move to target thread (0x55af5ad9b920)
```
and `Segmentation fault (core dumped)` error occur when I press any key.
That's all errors I got in console.
Can I fix this problem?
thank you

**Comment by swook** [comment]
I have had this issue in the past... and one solution that seemed to help was in using a system installation of OpenCV or manually compiling it from source.

Would you happen to be willing to give this a go?

**Comment by san9569** [comment]
@swook 
Thanks you to reply. So now I'm retrying to install OpenCV. And then, if this error occur again, I want to do anything I can..
I want to know about details of manually compiling.. 
Can you tell me more about that?
thank you
