### ISSUE TITLE
Real-time Inference

### ISSUE THREAD

**Issue by sahilrider** [NVlabs/few_shot_gaze#3]
How to do real time gaze detection using a webcam?

**Comment by shalinidemello** [comment]
The realtime demo with the webcam is slightly delayed. It is coming shortly. Please look out for it and thanks for your patience.

**Comment by ghost** [comment]
Is there any progress for real-time inference code ?

**Comment by shalinidemello** [comment]
Thanks for your patience! The real-time inference demo is now available.
