### ISSUE TITLE
Groud Truth of GazeCapture

### ISSUE THREAD

**Issue by Vampire-Vx** [NVlabs/few_shot_gaze#4]
As far as I know, the ground truth of GazeCapture dataset is 2D gaze points. However, your project is trained using 3D vectors as labels. Is there any conversion between them?

**Comment by Vampire-Vx** [comment]
Maybe you use the Surrey Face Model to get corresponding 3D face landmarks and select the mean of the 2 inner eye corners as origin. and the target point on phone screen as target to calculate the vector as gaze direction?

**Comment by swook** [comment]
That is exactly how it is done. Please find the relevant pre-processing code at https://github.com/swook/faze_preprocess/blob/master/create_hdf_files_for_faze.py#L178

and the relevant paper text in our Appendix A.1 of our paper at: https://arxiv.org/pdf/1905.01941.pdf

**Comment by Vampire-Vx** [comment]
> That is exactly how it is done. Please find the relevant pre-processing code at https://github.com/swook/faze_preprocess/blob/master/create_hdf_files_for_faze.py#L178
> 
> and the relevant paper text in our Appendix A.1 of our paper at: https://arxiv.org/pdf/1905.01941.pdf

Thanks for your quick reply and sharing of your code. I have read both your paper&code and I am wondering whether it is reasonable to use inferenced results from other face models as ground truth? I think it is not an accurate way to get ground truth. Thus, it is hard to judge the performace on GazeCapture.

**Comment by swook** [comment]
Hi, that is an accurate observation. However, all ground-truth (for example, human joint positions) are approximations to some extent so it is difficult to characterize how accurate the ground truth labels are. This is especially the case for gaze data, which cannot be explicitly measured (the landmarks concerning 3D gaze origin coordinates, specifically).

Having said this, we detail the steps we took to ensure the quality of our labels, specifically:

1. using a state-of-the-art facial landmarks detector for more reliable head pose estimation
2. using the nose landmarks for less ambiguity in the PnP-based head pose estimator
3. educated approximations for camera intrinsic parameters

A proof that this works very well is in the cross-dataset (trained on GC, tested on MPI) errors of 5.2 degrees - which is unprecedented in gaze estimation literature. The closest figures tend to be around the 7-degree mark.

**Comment by Vampire-Vx** [comment]
> Hi, that is an accurate observation. However, all ground-truth (for example, human joint positions) are approximations to some extent so it is difficult to characterize how accurate the ground truth labels are. This is especially the case for gaze data, which cannot be explicitly measured (the landmarks concerning 3D gaze origin coordinates, specifically).
> 
> Having said this, we detail the steps we took to ensure the quality of our labels, specifically:
> 
> 1. using a state-of-the-art facial landmarks detector for more reliable head pose estimation
> 2. using the nose landmarks for less ambiguity in the PnP-based head pose estimator
> 3. educated approximations for camera intrinsic parameters
> 
> A proof that this works very well is in the cross-dataset (trained on GC, tested on MPI) errors of 5.2 degrees - which is unprecedented in gaze estimation literature. The closest figures tend to be around the 7-degree mark.

Nice! Thanks for your kindly sharing of experiment details.
