### ISSUE TITLE
 Transpose of rotate matrix

### ISSUE THREAD

**Issue by Vampire-Vx** [NVlabs/few_shot_gaze#5]
https://github.com/NVlabs/few_shot_gaze/blob/d29edbe4681a2c96200746d8bd984a3480d8e343/src/models/dt_ed.py#L106
Not clear why the rotation matrix should be transposed? And the feature code should be post-multiplied?

**Comment by swook** [comment]
This is because when decoding (trans-coding) to a different image from the same person, we need the forward transform,

and when just encoding an image (this case), we need the backward (inverse) transform to take the representation to a normalized space.

I hope this helps.
