### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by nhathoang0110** [NVlabs/few_shot_gaze#8]
How to demo on my video that is not webcam ?
Thanks you

**Comment by swook** [comment]
The demo specifically aims to take a user through a few-shot calibration procedure to demonstrate improved accuracy in screen-space coordinates.

Thus, it would not be the most obvious thing to implement a video-only version - and thus we do not provide this. I hope this helps.

**Comment by Itamar651** [comment]
I got stuck on error in demo because of a library called PyGObject that for some reason I couldn't install using pip and without it I couldn't run the demo.py(using windows or mac). 

Do I must use PyGObject library?
Do you know why I field to install PyGObject using pip?
