### ISSUE TITLE
How do you get the gaze direction of GazeCapture dataset?

### ISSUE THREAD

**Issue by reyuri** [NVlabs/few_shot_gaze#9]
As I know, GazeCapture dataset doesn't include the gaze direction of each sample, so i am curious how do you acquire the gaze direction of that? Can you share the specific idea to compute the gaze direction of GazeCapture samples? 

Thanks for your great work ,and I'm looking forward your reply.

**Comment by swook** [comment]
The specific code for doing this can be found at https://github.com/swook/faze_preprocess

This code itself uses some intermediate predictions with which to perform the so-called _**data normalization**_ procedure for yielding the final image patches for use in training learning-based models.

The best reference for this procedure is https://www.perceptualui.org/publications/zhang18_etra.pdf

For the specific algorithms we selected for face detection and facial landmarks localization, please refer to Appendix A.1 of https://arxiv.org/abs/1905.01941

**Comment by reyuri** [comment]
Firstly, thanks for your reply . Then, I am sorry you might misread my question because of my inexplicit expression. I have already read those pre-process code and paper references ,but I am still confused about how did you get the groud-truth gaze direction of GazeCaputre,since the  dataset doesn't come with the gaze direction as original groud-truth info. More specifically,in my understanding, the GazeCapture dataset provides images and the (x,y) position of gaze dot on the phones as well as portable devices ,but doesn't provide the 3D gaze direction ,so how do you compute the 3D gaze dirction as groud-truth to train the model? If i misunderstand this ,please let me know.

**Comment by swook** [comment]
The data normalization procedure is the key to all of this. So I suggest going through the original implementation from Dr. Xucong Zhang, which can be found at this link: https://www.mpi-inf.mpg.de/departments/computer-vision-and-machine-learning/research/gaze-based-human-computer-interaction/revisiting-data-normalization-for-appearance-based-gaze-estimation/

My code is built on top of that code, which has to initially define a 6D gaze ray, formed of 3D origin and 3D target. The origin definition is somewhat arbitrary, but for similarity to anatomical truth, we take the average of the most relevant landmarks and use that as the 3D origin wrt the camera center. The 3D target in the case of GazeCapture is defined to be on the camera's `z=0` plane, as described in the original paper. We thus simply pad the x, y values (described in the original dataset in cm, and thus we need to convert this to mm) with a zero, and proceed.

The relevant code is at https://github.com/swook/faze_preprocess/blob/master/create_hdf_files_for_faze.py#L178 though the definition of the gaze target is handled separately and not apparent here.
